Dev
mate-academy/py-movie-moviesession-cinemahall pull request #188
Opened 2023-01-05 14:14 UTC by the-andrew-007

2023-01-05 19:02 UTC, katevasilenko commented on services/movie_session.py
> +# from datetime import time, date
Please remove

2023-01-05 19:05 UTC, katevasilenko commented on services/movie_session.py
> +    params = {
Not really good naming. Please provide more clear name of variable

2023-01-05 19:05 UTC, katevasilenko commented on services/movie_session.py
> +    not_none_params = {k: v for k, v in params.items() if v is not None}
The same

2023-01-06 11:54 UTC, Abnormaltype requested changes

2023-01-07 09:31 UTC, Vasyl-Smutok approved these changes
Good Job 👍

2024-04-21 18:10 UTC, closed without merging