develop
mate-academy/py-movie-moviesession-cinemahall pull request #333
Opened 2023-05-09 13:45 UTC by IvanGuculyak

2023-05-09 13:48 UTC, vasylhnatiuk requested changes
tests are failed

2023-05-09 18:54 UTC, ArsenPidhoretskyi requested changes

2023-05-09 18:54 UTC, ArsenPidhoretskyi commented on services/cinema_hall.py
> +) -> None:
It does not return None
It returns CinemaHall

2023-05-09 18:54 UTC, ArsenPidhoretskyi commented on services/cinema_hall.py
> +def get_cinema_halls() -> CinemaHall:
.all does not return one object

2023-05-09 18:54 UTC, ArsenPidhoretskyi commented on services/movie.py
> +        genres_ids: list[int] = None,
Use Optional[list[int]] because None as default provided
Fix in all places with all types

2023-05-09 18:54 UTC, ArsenPidhoretskyi commented on services/movie.py
> +) -> Movie:
Wrong return type annotations

2023-05-09 18:54 UTC, ArsenPidhoretskyi commented on services/movie.py
> +) -> None:
Wrong return type annotations

2023-05-09 18:54 UTC, ArsenPidhoretskyi commented on services/movie_session.py
> +) -> MovieSession:
Wrong return type annotations

2023-05-09 18:54 UTC, ArsenPidhoretskyi commented on services/movie_session.py
> +    movie_session = MovieSession.objects.all()
rename movie_session to movie_sessions

2023-05-09 18:54 UTC, ArsenPidhoretskyi commented on services/movie_session.py
> +        ).update(cinema_hall_id=cinema_hall_id)
No need to do 3 queries. You can do it by one query or use two queries:
1. Get object then set all new variables
2. Save object

2023-05-10 07:26 UTC, Grayder0152 approved these changes

2024-05-22 11:53 UTC, closed without merging