implemented movie_sessions
mate-academy/py-movie-moviesession-cinemahall pull request #392
Opened 2023-07-03 17:25 UTC by mariiahorbova

2023-07-03 19:13 UTC, oleksiikolii requested changes

2023-07-03 19:13 UTC, oleksiikolii commented on services/movie.py
> +            & Q(actors__pk__in=actors_ids)
You can remove this check if you put query into variable and than apply filters to this query if needed, eventually return this query

2023-07-03 19:13 UTC, oleksiikolii commented on services/movie_session.py
> +            show_time__date=session_date
Same here, you can do `movies = movies_sessions.filter(....)` and use one return in the end

2023-07-03 20:12 UTC, oleksiikolii approved these changes
Good job!

2023-07-04 15:25 UTC, LiudmylaKulinchenko requested changes

2023-07-04 15:25 UTC, LiudmylaKulinchenko commented on db/models.py
> +    @property
using the decorator is not necessary. You can remove it

2023-07-04 15:25 UTC, LiudmylaKulinchenko commented on services/cinema_hall.py
> +def create_cinema_hall(hall_name: str,
fix indentation here

2023-07-04 15:25 UTC, LiudmylaKulinchenko commented on services/movie_session.py
> +def create_movie_session(movie_show_time: str,
fix indentation

2023-07-04 15:25 UTC, LiudmylaKulinchenko commented on services/movie_session.py
> +        cinema_hall=CinemaHall(pk=cinema_hall_id)
Use checklist "Code Efficiency" first point

2023-07-04 15:25 UTC, LiudmylaKulinchenko commented on services/movie_session.py
> +        session_date: Optional[str] = None
If you specify a default value of `None` for a parameter, you don't need to use the `Optional` type hint

2023-07-04 15:25 UTC, LiudmylaKulinchenko commented on services/movie.py
> +                 genres_ids: Optional[list] = None,
You can remove Optional and use `list[int]` instead

2023-07-04 15:25 UTC, LiudmylaKulinchenko commented on services/movie_session.py
> +def update_movie_session(session_id: int,
Indentation is wrong in such cases. Fix everywhere

2023-07-04 15:28 UTC, LiudmylaKulinchenko commented on db/models.py
> +    genres = models.ManyToManyField(Genre)
Add related_name

2023-07-06 14:32 UTC, YuriiKindrat requested changes

2023-07-07 13:40 UTC, YuriiKindrat approved these changes

2024-03-13 20:00 UTC, closed without merging