py-movie-moviesession-cinemahall solution
mate-academy/py-movie-moviesession-cinemahall pull request #429
Opened 2023-08-13 17:15 UTC by sbilikepy

2023-08-13 17:53 UTC, vsmutok requested changes

2023-08-13 17:53 UTC, vsmutok commented on services/movie_session.py
> +        print(f"There is no session with id {session_id} in the DB")
I thin better to move `try ... except` block into get_movie_session_by_id method

2023-08-13 17:53 UTC, vsmutok commented on db/models.py
> +    )  # m-t-m
Please remove this comments

2023-08-13 17:53 UTC, vsmutok commented on services/movie.py
> +            print(f"Wrong Actor id: {e}")
DRY 

you repeat the `try ... except` block twice
I think it redundant here, but if you want to add exception handling, try to create decorator for it

2023-08-14 08:09 UTC, ArsenPidhoretskyi requested changes

2023-08-14 08:09 UTC, ArsenPidhoretskyi commented on services/movie.py
> +        genres_ids: List[int] = None,
```suggestion
        genres_ids: Optional[List[int]] = None,
```
Use Optional also because None as default

2023-08-14 08:09 UTC, ArsenPidhoretskyi commented on services/movie.py
> +        genres_ids: List[int] = None,
Fix with all types

2023-08-14 08:09 UTC, ArsenPidhoretskyi commented on services/movie.py
> +        )
Use .set

2023-08-14 08:09 UTC, ArsenPidhoretskyi commented on services/movie.py
> +        movie.actors.add(
Use .set

2023-08-14 08:09 UTC, ArsenPidhoretskyi commented on services/movie_session.py
> +        movie_show_time: datetime,
movie_show_time is module?
Because you use `import datetime` not `from datetime import datetime`

2023-08-14 08:09 UTC, ArsenPidhoretskyi commented on services/movie_session.py
> +        return MovieSession.objects.all()
```suggestion
    queryset = MovieSession.objects.all()
    if session_date:
        queryset = queryset.filter(
            show_time__date=session_date)
     return queryset
```

2023-08-14 08:09 UTC, ArsenPidhoretskyi commented on services/movie_session.py
> +        print(f"There is no session with id {movie_session_id} in the DB")
Use get_object_or_404

2023-08-14 08:09 UTC, ArsenPidhoretskyi commented on services/movie_session.py
> +        movie_session_to_update.movie = Movie.objects.get(id=movie_id)
You can set by id
```suggestion
        movie_session_to_update.movie_id = movie_id
```

2023-08-14 08:09 UTC, ArsenPidhoretskyi commented on services/movie_session.py
> +        )
```suggestion
        movie_session_to_update.cinema_hall_id = cinema_hall_id
```

2023-08-14 18:57 UTC, vsmutok approved these changes
Looks Good 👍

2026-07-30 15:20 UTC, closed without merging